"""
CPL Case Catalog — V2 Expanded

Three tiers:
  - same-day:   Complete guides in project knowledge. Delivered same day.
  - fast-build: High-data cases. Built from verified research. 24-48h.
  - on-request: Identified from course mapping. Built on order. 48-72h.

Alias clusters confirmed by research:
  - HTN Stage 2: Harvey Hoya, Anselmo Lopez, Herbie Romero, Felipe Garcia, Jessie Wood
  - Migraine with Aura: Bebe Babbitt, Marta Hernandez, Jessica Walbertz, Mabel Johnson
  - GAS Pharyngitis: Amanda Wheaton, Jenna James
  - Pediatric GE: Samantha Graves, Courtney Graham, 18-month unnamed (NRNP 6541)
  - CV Assessment: Marvin Webber (NR509), Marvin Webster (NURS 6512)
  - Low back pain: Tina Williams, Benjamin Cavill, unnamed 66yo female (NRNP 6531 Wk9)
"""

CASES = [

    # ══════════════════════════════════════════════════════════════
    # TIER 1: SAME-DAY — Complete guides in project knowledge
    # ══════════════════════════════════════════════════════════════

    {
        "slug": "harvey-hoya-htn",
        "title": "Harvey Hoya — Hypertension Stage 2",
        "patient_short": "57-year-old male",
        "chief_complaint": "High blood pressure noted at community health fair",
        "diagnosis": "Hypertension, Primary (Essential) — Stage 2 with target organ damage",
        "course": "NR 509 / NR 511 Week 5",
        "school": "Chamberlain University",
        "aliases": ["Harvey Hoya", "Anselmo Lopez", "Herbie Romero", "Felipe Garcia", "Jessie Wood"],
        "must_not_miss": "Obstructive Sleep Apnea (OSA)",
        "key_scoring_traps": [
            "AV nicking on fundoscopy = target organ damage (often missed)",
            "Laterally displaced PMI = LVH — must palpate, not just auscultate",
            "Stage 2 requires two-drug therapy per ACC/AHA 2017 — Lisinopril + HCTZ",
            "35+ pack-year smoking history must appear in key findings AND plan",
            "OSA referral required — snoring + HTN + overweight = must-not-miss",
        ],
        "tags": ["Cardiovascular", "Adult"],
        "preview_hpi_count": 35,
        "preview_pe_count": 28,
        "preview_dx_count": 5,
        "lead_time": "same-day",
        "data_level": "high",
        "courses": ["nr-509", "nr-511"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "bebe-babbitt-migraine",
        "title": "Bebe Babbitt — Migraine with Aura",
        "patient_short": "26-year-old female",
        "chief_complaint": "More frequent severe headaches",
        "diagnosis": "Migraine with Aura",
        "course": "NR 509 Week 6",
        "school": "Chamberlain University",
        "aliases": ["Bebe Babbitt", "Marta Hernandez", "Jessica Walbertz", "Mabel Johnson"],
        "must_not_miss": "Secondary headache — apply SNOOP4 screen; cluster headache",
        "key_scoring_traps": [
            "ORDER ZERO TESTS — normal exam, clinical diagnosis only",
            "Ordering CT or MRI = 'harmful to patient' flag → Tests score drops to 0%",
            "Scintillating scotomas is the clinical term for 'zig-zaggy lights'",
            "Photophobia/phonophobia must be documented in clinical language",
            "Pivotal communication question is scored — do not skip",
        ],
        "tags": ["Neurologic", "Adult"],
        "preview_hpi_count": 32,
        "preview_pe_count": 24,
        "preview_dx_count": 4,
        "lead_time": "same-day",
        "data_level": "high",
        "courses": ["nr-509"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "cynthia-francis-hyperlipidemia",
        "title": "Cynthia Francis — Hyperlipidemia",
        "patient_short": "53-year-old female",
        "chief_complaint": "Follow-up after abnormal lipid panel",
        "diagnosis": "Hyperlipidemia / Mixed dyslipidemia",
        "course": "NR 509 / NR 511",
        "school": "Chamberlain University",
        "aliases": ["Cynthia Francis"],
        "must_not_miss": "Untreated hypothyroidism as secondary cause of hyperlipidemia",
        "key_scoring_traps": [
            "TSH must be ordered — rules out hypothyroid as secondary cause",
            "Atorvastatin 20 mg starting dose, taken at bedtime (not morning)",
            "Lifestyle counseling required even when starting statin",
            "Continue thyroid hormone replacement concurrently if on it",
        ],
        "tags": ["Endocrine", "Adult"],
        "preview_hpi_count": 30,
        "preview_pe_count": 22,
        "preview_dx_count": 4,
        "lead_time": "same-day",
        "data_level": "high",
        "courses": ["nr-509", "nr-511"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "samantha-graves-gastroenteritis",
        "title": "Samantha Graves — Viral Gastroenteritis",
        "patient_short": "5-year-old female",
        "chief_complaint": "Vomiting and diarrhea ×2 days",
        "diagnosis": "Acute viral gastroenteritis with mild dehydration",
        "course": "NR 602 Week 5",
        "school": "Chamberlain University",
        "aliases": ["Samantha Graves", "Courtney Graham"],
        "must_not_miss": "Bacterial gastroenteritis; severe dehydration; intussusception",
        "key_scoring_traps": [
            "Order zero tests for uncomplicated pediatric viral GE — labs = harmful flag",
            "ORS (Pedialyte) small frequent sips — not antiemetics in mild dehydration",
            "Capillary refill and skin turgor are scored PE items",
            "Parent education on warning signs of worsening dehydration is faculty-scored",
        ],
        "tags": ["GI", "Pediatric"],
        "preview_hpi_count": 28,
        "preview_pe_count": 26,
        "preview_dx_count": 4,
        "lead_time": "same-day",
        "data_level": "high",
        "courses": ["nr-602", "nrnp-6541"],
        "schools": ["chamberlain", "walden"],
    },
    {
        "slug": "kennedy-poole-adhd",
        "title": "Kennedy Poole — ADHD, Inattentive",
        "patient_short": "10-year-old female",
        "chief_complaint": "Slipping grades and academic decline",
        "diagnosis": "ADHD, Predominantly Inattentive (F90.0)",
        "course": "NR 602 Week 4",
        "school": "Chamberlain University",
        "aliases": ["Kennedy Poole"],
        "must_not_miss": "Vision impairment; hearing impairment; learning disorder; depression; absence seizures",
        "key_scoring_traps": [
            "History goes to PARENT first — pediatric opener is 'How can I help her today?'",
            "Vanderbilt scales (parent AND teacher versions) — must order both",
            "Methylphenidate ER 18 mg every morning — Schedule II, 0 refills",
            "Baseline ECG required before stimulant initiation",
            "Child AND parent interview — both are scored separately",
        ],
        "tags": ["Mental Health", "Pediatric"],
        "preview_hpi_count": 38,
        "preview_pe_count": 22,
        "preview_dx_count": 5,
        "lead_time": "same-day",
        "data_level": "high",
        "courses": ["nr-602"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "victoria-lewis-rash",
        "title": "Victoria Lewis — Dermatologic Rash",
        "patient_short": "Adult female",
        "chief_complaint": "Skin rash — differential diagnosis",
        "diagnosis": "Dermatologic rash (confirmed at delivery)",
        "course": "NR 511 Week 7",
        "school": "Chamberlain University",
        "aliases": ["Victoria Lewis"],
        "must_not_miss": "Confirmed at delivery — rash DDx includes SLE, contact dermatitis, tinea",
        "key_scoring_traps": [
            "Dermoscopy / skin distribution pattern are key PE findings",
            "Full skin exam required — not just the presenting site",
            "Drug history critical — many rashes are medication-induced",
            "NR511 DDx focus — ranking and clinical reasoning weighted heavily",
        ],
        "tags": ["Dermatology", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "same-day",
        "data_level": "medium",
        "courses": ["nr-511"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "betty-burns-pt1",
        "title": "Betty Burns — Part 1",
        "patient_short": "Adult female",
        "chief_complaint": "Confirmed at intake",
        "diagnosis": "Confirmed at intake",
        "course": "Chamberlain — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Betty Burns"],
        "must_not_miss": "Confirmed at delivery",
        "key_scoring_traps": [
            "Part 1 of two-part case sequence — order Part 2 together for best value",
            "Full scoring strategy provided on delivery",
        ],
        "tags": ["Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "same-day",
        "data_level": "medium",
        "courses": ["nr-509", "nr-511"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "betty-burns-pt2",
        "title": "Betty Burns — Part 2",
        "patient_short": "Adult female",
        "chief_complaint": "Confirmed at intake",
        "diagnosis": "Confirmed at intake",
        "course": "Chamberlain — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Betty Burns"],
        "must_not_miss": "Confirmed at delivery",
        "key_scoring_traps": [
            "Continuation of Part 1 — management plan builds on prior visit",
            "Full scoring strategy provided on delivery",
        ],
        "tags": ["Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "same-day",
        "data_level": "medium",
        "courses": ["nr-509", "nr-511"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "christine-smith-pyelonephritis",
        "title": "Christine Smith — Pyelonephritis",
        "patient_short": "Adult female",
        "chief_complaint": "Flank pain, fever, dysuria",
        "diagnosis": "Acute pyelonephritis",
        "course": "NRNP 6531 Week 7",
        "school": "Walden University",
        "aliases": ["Christine Smith"],
        "must_not_miss": "Sepsis / urosepsis; obstructive nephrolithiasis; renal abscess",
        "key_scoring_traps": [
            "CVA tenderness — must elicit bilaterally and document findings",
            "Empiric antibiotics BEFORE culture results — don't wait",
            "Urine culture + sensitivity is required (not just dipstick)",
            "Inpatient vs outpatient criteria must be explicitly addressed in plan",
        ],
        "tags": ["GU", "Adult"],
        "preview_hpi_count": 30,
        "preview_pe_count": 24,
        "preview_dx_count": 4,
        "lead_time": "same-day",
        "data_level": "high",
        "courses": ["nrnp-6531"],
        "schools": ["walden"],
    },

    # ══════════════════════════════════════════════════════════════
    # TIER 2: FAST-BUILD — High research data, 24-48h delivery
    # ══════════════════════════════════════════════════════════════

    {
        "slug": "amanda-wheaton-pharyngitis",
        "title": "Amanda Wheaton — GAS Pharyngitis",
        "patient_short": "23-year-old female",
        "chief_complaint": "Sore throat and fever ×3 days",
        "diagnosis": "Group A Streptococcal pharyngitis",
        "course": "NR 509 HEENT Week",
        "school": "Chamberlain University",
        "aliases": ["Amanda Wheaton", "Jenna James"],
        "must_not_miss": "Peritonsillar abscess; infectious mononucleosis; epiglottitis",
        "key_scoring_traps": [
            "Centor criteria must be applied — all 4 criteria scored",
            "Absence of cough is a positive Centor finding — do not miss it",
            "Penicillin V 500 mg BID × 10 full days — shorter courses lose points",
            "Rapid strep test required; throat culture if negative",
            "Mono must be on the DDx — Monospot if mono suspected",
        ],
        "tags": ["ENT", "Adult"],
        "preview_hpi_count": 28,
        "preview_pe_count": 22,
        "preview_dx_count": 4,
        "lead_time": "fast-build",
        "data_level": "high",
        "courses": ["nr-509"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "marvin-webber-cardiovascular",
        "title": "Marvin Webber — Cardiovascular Assessment",
        "patient_short": "Adult male",
        "chief_complaint": "Cardiovascular complaint — history and assessment",
        "diagnosis": "Cardiovascular pathology (confirmed at delivery)",
        "course": "NR 509 Practice Case / NURS 6512",
        "school": "Chamberlain University / Walden University",
        "aliases": ["Marvin Webber", "Marvin Webster"],
        "must_not_miss": "ACS; heart failure; arrhythmia",
        "key_scoring_traps": [
            "JVP assessment — must measure and document",
            "Peripheral pulses bilateral comparison — scored PE item",
            "12-lead ECG required in cardiovascular workup",
            "Cardiac risk factor documentation must be exhaustive",
            "Used as practice case in NR509 — 'complete 3 times before graded attempt'",
        ],
        "tags": ["Cardiovascular", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "high",
        "courses": ["nr-509", "nurs-6512"],
        "schools": ["chamberlain", "walden"],
    },
    {
        "slug": "nrnp6531-wk7-pneumonia",
        "title": "NRNP 6531 Week 7 — Community-Acquired Pneumonia",
        "patient_short": "28-year-old male",
        "chief_complaint": "Productive cough and fatigue ×4 days",
        "diagnosis": "Community-acquired pneumonia (CAP) — right lower lobe",
        "course": "NRNP 6531 Week 7",
        "school": "Walden University",
        "aliases": ["NRNP 6531 Case #7"],
        "must_not_miss": "Tuberculosis; lung abscess; pulmonary embolism",
        "key_scoring_traps": [
            "History must include alcohol use — heavy use is a CAP risk factor scored here",
            "Unilateral auscultation findings — must localize and document (RLL)",
            "CURB-65 score must be calculated for inpatient vs outpatient decision",
            "Need ≥85% on history section — 2026 rubric is strict on this case",
            "Sputum culture + sensitivity required alongside chest X-ray",
        ],
        "tags": ["Respiratory", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "high",
        "courses": ["nrnp-6531"],
        "schools": ["walden"],
    },
    {
        "slug": "caleb-metz-adolescent",
        "title": "Caleb Metz — Adolescent Primary Care",
        "patient_short": "13-year-old male",
        "chief_complaint": "Adolescent complaint (confirmed at delivery)",
        "diagnosis": "Confirmed at delivery",
        "course": "NURS 6512 Week 10",
        "school": "Walden University",
        "aliases": ["Caleb Metz"],
        "must_not_miss": "Confirmed at delivery — adolescent cases: depression, substance use, STI always on DDx",
        "key_scoring_traps": [
            "CONFIDENTIALITY must be addressed with the adolescent — scored communication item",
            "HEADSS assessment framework applies to all adolescent iHuman cases",
            "Parent in room vs. private interview with patient — navigation is scored",
            "Immunization status always required for adolescent encounters",
        ],
        "tags": ["Pediatric", "Adolescent"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "high",
        "courses": ["nurs-6512"],
        "schools": ["walden"],
    },
    {
        "slug": "emma-ryan-pediatric-uri",
        "title": "Emma Ryan — Pediatric URI",
        "patient_short": "2-year-old female",
        "chief_complaint": "Runny nose, cough, and fever",
        "diagnosis": "Viral upper respiratory infection / otitis media (confirm at delivery)",
        "course": "NRNP 6541 / NR 602",
        "school": "Walden University / Chamberlain University",
        "aliases": ["Emma Ryan"],
        "must_not_miss": "Bacterial pneumonia; epiglottitis; croup",
        "key_scoring_traps": [
            "All history questions directed to PARENT — 2-year-old cannot self-report",
            "Otoscopic exam is required — OM is the #1 complication of pediatric URI",
            "No antibiotics for viral URI — prescribing is a harmful flag",
            "Parent education on fever management and when to return",
        ],
        "tags": ["Respiratory", "Pediatric"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "medium",
        "courses": ["nrnp-6541", "nr-602"],
        "schools": ["walden", "chamberlain"],
    },
    {
        "slug": "benjamin-cavill-low-back",
        "title": "Benjamin Cavill — Low Back Pain",
        "patient_short": "Adult / 66-year-old female (alias-dependent)",
        "chief_complaint": "Low back pain",
        "diagnosis": "Acute low back pain — MSK vs radiculopathy (confirmed at delivery)",
        "course": "NRNP 6531 Week 9",
        "school": "Walden University",
        "aliases": ["Benjamin Cavill", "Tina Williams", "J.C.", "Unnamed 66yo female"],
        "must_not_miss": "Cauda equina syndrome; vertebral fracture; malignancy; AAA",
        "key_scoring_traps": [
            "Red flag screen required: bowel/bladder dysfunction, saddle anesthesia",
            "Neurologic exam of lower extremities is fully scored",
            "Straight leg raise test — must perform and document result",
            "Imaging not indicated for uncomplicated acute LBP — ordering = harmful flag",
            "NSAIDs + physical therapy are the evidence-based first-line combination",
        ],
        "tags": ["Musculoskeletal", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "medium",
        "courses": ["nrnp-6531"],
        "schools": ["walden"],
    },
    {
        "slug": "kathleen-parks-nr509",
        "title": "Kathleen Parks — NR509 Week 6",
        "patient_short": "Adult female",
        "chief_complaint": "Confirmed at delivery",
        "diagnosis": "Confirmed at delivery",
        "course": "NR 509 Week 6",
        "school": "Chamberlain University",
        "aliases": ["Kathleen Parks"],
        "must_not_miss": "Confirmed at delivery",
        "key_scoring_traps": [
            "High-traffic NR509 case — multiple commercial guides exist, verify platform version",
            "Full scoring strategy provided on delivery",
        ],
        "tags": ["Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "high",
        "courses": ["nr-509"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "nrnp6541-encopresis",
        "title": "NRNP 6541 Week 7 — Pediatric Encopresis",
        "patient_short": "School-age child (toilet-trained)",
        "chief_complaint": "Fecal soiling / encopresis",
        "diagnosis": "Encopresis (F98.1) with functional constipation (K59.00)",
        "course": "NRNP 6541 Week 7",
        "school": "Walden University",
        "aliases": ["NRNP 6541 Encopresis Case"],
        "must_not_miss": "Hirschsprung disease; celiac disease; hypothyroidism; abuse",
        "key_scoring_traps": [
            "Functional vs organic encopresis distinction — most students over-order tests",
            "Behavioral intervention is first-line, not laxatives alone",
            "Hirschsprung disease must be on DDx despite being less likely",
            "Dietary history (fiber, fluid intake) is a scored history item",
            "Abdominal X-ray to confirm fecal loading — not to diagnose the cause",
        ],
        "tags": ["GI", "Pediatric"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "high",
        "courses": ["nrnp-6541"],
        "schools": ["walden"],
    },

    # ══════════════════════════════════════════════════════════════
    # TIER 3: ON-REQUEST — Identified from course mapping
    # ══════════════════════════════════════════════════════════════

    # ── Shadow Health ──
    {
        "slug": "tina-jones-shadow-health",
        "title": "Tina Jones — Shadow Health Complete Series",
        "patient_short": "28-year-old female",
        "chief_complaint": "Multiple — full Shadow Health case series",
        "diagnosis": "Diabetes Type 2 + multiple system assessments",
        "course": "NURS 6512 / Multiple programs",
        "school": "Walden University / Multiple",
        "aliases": ["Tina Jones"],
        "must_not_miss": "DM2 complications; depression; neuropathy",
        "key_scoring_traps": [
            "Shadow Health scoring is different from iHuman — DCE empathy score matters",
            "Pertinent negatives must be explicitly documented in Shadow Health",
            "HEENT, Cardiovascular, Respiratory, Abdominal, MSK all assessed separately",
            "Penicillin allergy documented — affects antibiotic choices throughout",
        ],
        "tags": ["Shadow Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "fast-build",
        "data_level": "high",
        "courses": ["nurs-6512"],
        "schools": ["walden"],
    },

    # ── Walden NRNP 6531 remaining weeks ──
    {
        "slug": "nrnp6531-wk2-gi",
        "title": "NRNP 6531 Week 2 — GI Case",
        "patient_short": "Adult patient",
        "chief_complaint": "GI complaint (confirmed at delivery)",
        "diagnosis": "GI pathology — GERD, PUD, or IBS (confirmed at delivery)",
        "course": "NRNP 6531 Week 2",
        "school": "Walden University",
        "aliases": ["NRNP 6531 Week 2"],
        "must_not_miss": "GI malignancy; IBD; mesenteric ischemia",
        "key_scoring_traps": [
            "Described as 'tricky' in tutor forums — high help-seeking volume",
            "H. pylori testing decision is a key scored item",
            "Alarm symptoms must be actively screened — unintentional weight loss, dysphagia",
        ],
        "tags": ["GI", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6531"],
        "schools": ["walden"],
    },
    {
        "slug": "nrnp6531-wk4-cardiovascular",
        "title": "NRNP 6531 Week 4 — Cardiovascular Case",
        "patient_short": "Adult patient",
        "chief_complaint": "Cardiovascular complaint (confirmed at delivery)",
        "diagnosis": "Adult CV condition — HF, angina, or arrhythmia (confirmed at delivery)",
        "course": "NRNP 6531 Week 4",
        "school": "Walden University",
        "aliases": ["NRNP 6531 Week 4"],
        "must_not_miss": "ACS; PE; aortic dissection",
        "key_scoring_traps": [
            "BNP ordering decision — must justify in plan",
            "Echo referral vs. stress test — which is appropriate scored",
            "Bilateral BP comparison required",
        ],
        "tags": ["Cardiovascular", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6531"],
        "schools": ["walden"],
    },

    # ── Walden NRNP 6541 remaining ──
    {
        "slug": "adam-barnes-5yo",
        "title": "Adam Barnes — 5-Year-Old Primary Care",
        "patient_short": "5-year-old male",
        "chief_complaint": "Pediatric complaint (confirmed at delivery)",
        "diagnosis": "Confirmed at delivery",
        "course": "NRNP 6541 Week 2",
        "school": "Walden University",
        "aliases": ["Adam Barnes"],
        "must_not_miss": "Developmental delay; abuse; serious bacterial infection",
        "key_scoring_traps": [
            "Well-child visit components are scored — developmental milestones required",
            "Immunization review is always scored at this age",
            "Parent education on age-appropriate safety is faculty-scored",
        ],
        "tags": ["Pediatric"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6541"],
        "schools": ["walden"],
    },
    {
        "slug": "peds-18mo-vomiting",
        "title": "18-Month-Old — Vomiting and Diarrhea",
        "patient_short": "18-month-old child",
        "chief_complaint": "Vomiting and diarrhea (acute GE)",
        "diagnosis": "Acute viral gastroenteritis with dehydration assessment",
        "course": "NRNP 6541",
        "school": "Walden University",
        "aliases": ["NRNP 6541 GE Case", "18-month vomiting"],
        "must_not_miss": "Intussusception; pyloric stenosis; bacterial enteritis; severe dehydration",
        "key_scoring_traps": [
            "Dehydration severity scoring — mild vs moderate vs severe criteria",
            "ORS protocol — volumes and frequency are scored in the management plan",
            "No antiemetics in mild-moderate dehydration — ordering may flag harmful",
            "Stool characteristics are a scored history item — bloody stool changes DDx",
        ],
        "tags": ["GI", "Pediatric"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6541"],
        "schools": ["walden"],
    },

    # ── Walden NURS 6512 remaining ──
    {
        "slug": "nurs6512-nr509-wk1-uri",
        "title": "NR509 Week 1 — Adult URI Practice Case",
        "patient_short": "Adult with cough, sore throat, fever",
        "chief_complaint": "Cough, sore throat, and fever",
        "diagnosis": "Viral upper respiratory infection",
        "course": "NR 509 Week 1 (Practice case)",
        "school": "Chamberlain University",
        "aliases": ["NR509 Week 1 Practice", "Cough and Sore Throat Case"],
        "must_not_miss": "Bacterial pneumonia; influenza; COVID-19",
        "key_scoring_traps": [
            "Practice case used for iHuman orientation — scored like a real case",
            "Childhood asthma history in this patient — must explore and document",
            "No antibiotics for viral URI — antibiotic prescribing = harmful flag",
            "Pulmonary auscultation must cover all zones",
        ],
        "tags": ["Respiratory", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "high",
        "courses": ["nr-509"],
        "schools": ["chamberlain"],
    },

    # ── Gap plays: Women's Health (NRNP 6552) ──
    {
        "slug": "nrnp6552-prenatal",
        "title": "NRNP 6552 — Prenatal Visit",
        "patient_short": "Pregnant adult female",
        "chief_complaint": "Prenatal care visit",
        "diagnosis": "Normal obstetric care / prenatal assessment",
        "course": "NRNP 6552",
        "school": "Walden University",
        "aliases": ["NRNP 6552 Prenatal Case"],
        "must_not_miss": "Preeclampsia; gestational diabetes; ectopic pregnancy",
        "key_scoring_traps": [
            "Fundal height measurement is a scored PE item",
            "GDM screening — timing and test selection are scored",
            "Group B Strep screening — week of gestation triggers the order",
            "Fetal movement documentation is a scored history item",
        ],
        "tags": ["Women's Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "low",
        "courses": ["nrnp-6552"],
        "schools": ["walden"],
    },
    {
        "slug": "nrnp6552-abnormal-uterine-bleeding",
        "title": "NRNP 6552 — Abnormal Uterine Bleeding",
        "patient_short": "Adult female",
        "chief_complaint": "Irregular or heavy menstrual bleeding",
        "diagnosis": "Abnormal uterine bleeding — etiology confirmed at delivery",
        "course": "NRNP 6552",
        "school": "Walden University",
        "aliases": ["NRNP 6552 AUB Case"],
        "must_not_miss": "Endometrial cancer; coagulopathy; ectopic pregnancy",
        "key_scoring_traps": [
            "PALM-COEIN classification framework must be applied",
            "Pregnancy test before any other workup — always first",
            "Pelvic exam and bimanual exam are scored PE items",
            "CBC + coagulation studies are required, not optional",
        ],
        "tags": ["Women's Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "low",
        "courses": ["nrnp-6552"],
        "schools": ["walden"],
    },
    {
        "slug": "nrnp6552-contraception",
        "title": "NRNP 6552 — Contraception Counseling",
        "patient_short": "Adult female",
        "chief_complaint": "Contraception counseling visit",
        "diagnosis": "Contraception selection — method confirmed at delivery",
        "course": "NRNP 6552",
        "school": "Walden University",
        "aliases": ["NRNP 6552 Contraception Case"],
        "must_not_miss": "Thrombophilia (contraindication to COCs); undiagnosed pregnancy; STI",
        "key_scoring_traps": [
            "WHO Medical Eligibility Criteria must drive contraception selection",
            "History of migraine with aura = COC contraindication — critical scored item",
            "STI screening is always indicated at reproductive health visit",
            "Shared decision-making documentation is faculty-scored",
        ],
        "tags": ["Women's Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "low",
        "courses": ["nrnp-6552"],
        "schools": ["walden"],
    },

    # ── Gap plays: Psychiatric (NRNP 6568) ──
    {
        "slug": "nrnp6568-mdd",
        "title": "NRNP 6568 — Major Depressive Disorder",
        "patient_short": "Adult patient",
        "chief_complaint": "Depressed mood, fatigue, anhedonia",
        "diagnosis": "Major depressive disorder, moderate severity",
        "course": "NRNP 6568",
        "school": "Walden University",
        "aliases": ["NRNP 6568 MDD Case"],
        "must_not_miss": "Bipolar disorder; suicidal ideation; hypothyroidism; substance use",
        "key_scoring_traps": [
            "PHQ-9 administration is required — verbatim scoring matters",
            "Suicide risk assessment must be explicit — not implied",
            "TSH ordered to rule out hypothyroid as reversible cause",
            "Bipolar must be screened BEFORE starting antidepressant — MDQ or screening questions",
            "SSRI first-line with 2-week tolerability follow-up documented",
        ],
        "tags": ["Mental Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "low",
        "courses": ["nrnp-6568"],
        "schools": ["walden"],
    },
    {
        "slug": "nrnp6568-anxiety-gad",
        "title": "NRNP 6568 — Generalized Anxiety Disorder",
        "patient_short": "Adult patient",
        "chief_complaint": "Persistent worry, restlessness, sleep disturbance",
        "diagnosis": "Generalized anxiety disorder (GAD)",
        "course": "NRNP 6568",
        "school": "Walden University",
        "aliases": ["NRNP 6568 GAD Case"],
        "must_not_miss": "Panic disorder; hyperthyroidism; substance use; PTSD",
        "key_scoring_traps": [
            "GAD-7 administration is required",
            "TSH + drug screen to rule out organic cause",
            "SSRI/SNRI first-line — Buspirone is an adjunct, not monotherapy",
            "Psychotherapy referral is required in the management plan",
        ],
        "tags": ["Mental Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "low",
        "courses": ["nrnp-6568"],
        "schools": ["walden"],
    },
    {
        "slug": "nrnp6568-bipolar",
        "title": "NRNP 6568 — Bipolar Disorder",
        "patient_short": "Adult patient",
        "chief_complaint": "Mood instability, elevated energy episodes",
        "diagnosis": "Bipolar I or II disorder (confirmed at delivery)",
        "course": "NRNP 6568",
        "school": "Walden University",
        "aliases": ["NRNP 6568 Bipolar Case"],
        "must_not_miss": "Schizoaffective disorder; substance-induced mood disorder; ADHD",
        "key_scoring_traps": [
            "Antidepressant monotherapy = harmful in bipolar — critical trap",
            "Mood stabilizer must be first-line: Lithium, Valproate, or atypical antipsychotic",
            "MDQ screen or detailed manic episode history is scored",
            "Thyroid and renal function required before Lithium",
        ],
        "tags": ["Mental Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "low",
        "courses": ["nrnp-6568"],
        "schools": ["walden"],
    },
    {
        "slug": "nrnp6568-psychosis",
        "title": "NRNP 6568 — First-Episode Psychosis",
        "patient_short": "Adult patient",
        "chief_complaint": "Hallucinations, disorganized thinking",
        "diagnosis": "Psychosis — schizophrenia spectrum (confirmed at delivery)",
        "course": "NRNP 6568",
        "school": "Walden University",
        "aliases": ["NRNP 6568 Psychosis Case"],
        "must_not_miss": "Substance-induced psychosis; bipolar with psychotic features; medical cause",
        "key_scoring_traps": [
            "Medical workup required for first-episode psychosis — CBC, CMP, TSH, drug screen",
            "Safety assessment including homicidal ideation is scored",
            "Atypical antipsychotic selection with metabolic monitoring plan",
            "Family education and ACT referral are management plan items",
        ],
        "tags": ["Mental Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "low",
        "courses": ["nrnp-6568"],
        "schools": ["walden"],
    },

    # ── Additional Adult Primary Care ──
    {
        "slug": "tanner-bell-uri",
        "title": "Tanner Bell — Pediatric URI",
        "patient_short": "4-year-old male",
        "chief_complaint": "Cough and runny nose ×5 days",
        "diagnosis": "Viral upper respiratory infection",
        "course": "NR 602",
        "school": "Chamberlain University",
        "aliases": ["Tanner Bell"],
        "must_not_miss": "Bacterial pneumonia; otitis media; RSV bronchiolitis",
        "key_scoring_traps": [
            "No chest X-ray for uncomplicated URI — ordering may flag harmful",
            "Symptomatic management only — no antibiotics",
            "Otoscopic exam required — OM is the most common complication",
            "Parent education on duration and red flags is faculty-scored",
        ],
        "tags": ["Respiratory", "Pediatric"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nr-602"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "lori-jacobs-uti",
        "title": "Lori Jacobs — Uncomplicated UTI",
        "patient_short": "Adult female",
        "chief_complaint": "Dysuria and urinary frequency",
        "diagnosis": "Uncomplicated urinary tract infection",
        "course": "NR 511",
        "school": "Chamberlain University",
        "aliases": ["Lori Jacobs"],
        "must_not_miss": "Pyelonephritis; STI (chlamydia, gonorrhea); pregnancy",
        "key_scoring_traps": [
            "Pregnancy test before antibiotics in all reproductive-age females",
            "Nitrofurantoin 100 mg BID × 5 days — first-line per IDSA",
            "Urine dipstick + culture and sensitivity",
            "STI screen at reproductive health visits — always offer",
        ],
        "tags": ["GU", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nr-511"],
        "schools": ["chamberlain"],
    },
    {
        "slug": "geriatric-fall-risk",
        "title": "Geriatric Patient — Fall Risk Assessment",
        "patient_short": "Older adult",
        "chief_complaint": "Recent fall, mobility concern",
        "diagnosis": "Multifactorial fall risk",
        "course": "NRNP 6542 / NRNP 6531",
        "school": "Walden University",
        "aliases": ["Geriatric Fall Case"],
        "must_not_miss": "Syncope; medication-induced orthostasis; subdural hematoma; cardiac arrhythmia",
        "key_scoring_traps": [
            "Orthostatic vital signs are required — not optional",
            "Beers Criteria medication review must be documented",
            "Timed Up and Go (TUG) test is a scored PE item",
            "PT referral and home safety assessment are management plan items",
        ],
        "tags": ["Geriatric", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6542", "nrnp-6531"],
        "schools": ["walden"],
    },
    {
        "slug": "adult-depression-screen",
        "title": "Adult — Major Depressive Disorder",
        "patient_short": "Adult patient",
        "chief_complaint": "Low mood and fatigue",
        "diagnosis": "Major depressive disorder",
        "course": "NRNP 6541 / NRNP 6568",
        "school": "Walden University",
        "aliases": ["Depression Screen Case"],
        "must_not_miss": "Bipolar disorder; suicide risk; hypothyroidism; substance use",
        "key_scoring_traps": [
            "PHQ-9 + GAD-7 must be administered",
            "Suicide risk assessment must be explicit in the SOAP note",
            "TSH ordered to rule out hypothyroid",
            "SSRI selection with tolerability monitoring timeline",
        ],
        "tags": ["Mental Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6541", "nrnp-6568"],
        "schools": ["walden"],
    },
    {
        "slug": "type-2-diabetes-new",
        "title": "Adult — New Type 2 Diabetes Diagnosis",
        "patient_short": "Adult patient",
        "chief_complaint": "Polyuria, polydipsia, weight loss",
        "diagnosis": "Diabetes mellitus, type 2 — new diagnosis",
        "course": "NR 511 / NRNP 6531",
        "school": "Chamberlain University / Walden University",
        "aliases": ["New T2DM Case"],
        "must_not_miss": "DKA; HHS; type 1 DM; MODY",
        "key_scoring_traps": [
            "HbA1c + fasting glucose + C-peptide panel required",
            "Metformin 500 mg BID with meals — titrate gradually",
            "Dilated eye exam referral is a required management plan item",
            "DSME referral must be documented — diabetes self-management education",
        ],
        "tags": ["Endocrine", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nr-511", "nrnp-6531"],
        "schools": ["chamberlain", "walden"],
    },
    {
        "slug": "copd-exacerbation",
        "title": "Adult — COPD Exacerbation",
        "patient_short": "Adult patient, smoker",
        "chief_complaint": "Worsening dyspnea and purulent sputum",
        "diagnosis": "Acute exacerbation of COPD",
        "course": "NRNP 6531 / NRNP 6542",
        "school": "Walden University",
        "aliases": ["COPD Exacerbation Case"],
        "must_not_miss": "Pneumonia; pulmonary embolism; pneumothorax; heart failure",
        "key_scoring_traps": [
            "Spirometry (FEV1/FVC ratio) is the diagnostic standard — must order",
            "GOLD classification staging must be documented",
            "Short-acting bronchodilator is first-line — not LABA initiation",
            "Smoking cessation counseling is always a required plan item",
        ],
        "tags": ["Respiratory", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6531", "nrnp-6542"],
        "schools": ["walden"],
    },
    {
        "slug": "heart-failure-management",
        "title": "Adult — Heart Failure Management",
        "patient_short": "Adult patient",
        "chief_complaint": "Worsening dyspnea, bilateral leg swelling",
        "diagnosis": "Heart failure with reduced ejection fraction (HFrEF)",
        "course": "NRNP 6531 / NRNP 6542",
        "school": "Walden University",
        "aliases": ["CHF Case", "Heart Failure Case"],
        "must_not_miss": "ACS triggering decompensation; cardiac tamponade; PE",
        "key_scoring_traps": [
            "BNP or NT-proBNP is required to confirm HF diagnosis",
            "Echo for EF assessment — HFrEF vs HFpEF changes management",
            "ACEi/ARB + beta-blocker + diuretic = guideline-directed trio",
            "Daily weight monitoring is a required patient education item",
        ],
        "tags": ["Cardiovascular", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nrnp-6531", "nrnp-6542"],
        "schools": ["walden"],
    },
    {
        "slug": "hypothyroidism-adult",
        "title": "Adult — Hypothyroidism, New Diagnosis",
        "patient_short": "Adult female",
        "chief_complaint": "Fatigue, weight gain, cold intolerance",
        "diagnosis": "Primary hypothyroidism",
        "course": "NR 509 / NR 511",
        "school": "Chamberlain University",
        "aliases": ["Hypothyroid Case"],
        "must_not_miss": "Secondary hypothyroidism (pituitary); Hashimoto thyroiditis; depression",
        "key_scoring_traps": [
            "TSH is the initial test — NOT free T4 alone",
            "Levothyroxine dosing by body weight — 1.6 mcg/kg/day",
            "Recheck TSH in 6–8 weeks after initiation",
            "Anti-TPO antibodies confirm Hashimoto — affects counseling",
        ],
        "tags": ["Endocrine", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "lead_time": "on-request",
        "data_level": "medium",
        "courses": ["nr-509", "nr-511"],
        "schools": ["chamberlain"],
    },
]

# ══════════════════════════════════════════════════════════════════════
# PRICING
# ══════════════════════════════════════════════════════════════════════
PRICING = {
    "single":  {"price": 150, "label": "Single guide", "saves": 0,
                "blurb": "One complete case, delivered same day."},
    "bundle3": {"price": 390, "label": "3-case bundle", "saves": 60,
                "blurb": "Save $60. Mix any 3 cases."},
    "bundle5": {"price": 540, "label": "5-case bundle", "saves": 210,
                "blurb": "Save $210. Best value for a full term."},
}

# ══════════════════════════════════════════════════════════════════════
# COURSE REGISTRY — maps course codes to human labels
# ══════════════════════════════════════════════════════════════════════
COURSES = {
    "nr-509":    {"label": "NR 509", "full": "Advanced Physical Assessment", "school": "Chamberlain"},
    "nr-511":    {"label": "NR 511", "full": "Differential Diagnosis",       "school": "Chamberlain"},
    "nr-602":    {"label": "NR 602", "full": "Primary Care — Childbearing/Childrearing Family", "school": "Chamberlain"},
    "nurs-6512": {"label": "NURS 6512", "full": "Advanced Health Assessment", "school": "Walden"},
    "nrnp-6531": {"label": "NRNP 6531", "full": "Primary Care of Adults",    "school": "Walden"},
    "nrnp-6541": {"label": "NRNP 6541", "full": "Primary Care — Adolescents & Children", "school": "Walden"},
    "nrnp-6542": {"label": "NRNP 6542", "full": "Advanced Practice — Adults & Older Adults", "school": "Walden"},
    "nrnp-6552": {"label": "NRNP 6552", "full": "Women's Health",            "school": "Walden"},
    "nrnp-6568": {"label": "NRNP 6568", "full": "Psychiatric Mental Health NP", "school": "Walden"},
}

# ══════════════════════════════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════════════════════════════
def by_lead_time(lt):
    return [c for c in CASES if c.get("lead_time") == lt]

def by_slug(slug):
    for c in CASES:
        if c["slug"] == slug:
            return c
    return None

def by_course(course_code):
    return [c for c in CASES if course_code in c.get("courses", [])]

def by_tag(tag):
    return [c for c in CASES if tag in c.get("tags", [])]

def search(query):
    q = query.lower()
    return [c for c in CASES if
            q in c["title"].lower() or
            q in c.get("chief_complaint", "").lower() or
            q in c.get("diagnosis", "").lower() or
            q in " ".join(c.get("aliases", [])).lower() or
            q in " ".join(c.get("tags", [])).lower() or
            q in c.get("course", "").lower()]

if __name__ == "__main__":
    same = by_lead_time("same-day")
    fast = by_lead_time("fast-build")
    req  = by_lead_time("on-request")
    print(f"\nCPL Case Catalog V2")
    print(f"{'─'*40}")
    print(f"  Same-day  (complete guides):  {len(same)}")
    print(f"  Fast-build (24-48h):           {len(fast)}")
    print(f"  On-request (48-72h):           {len(req)}")
    print(f"  {'─'*30}")
    print(f"  TOTAL:                         {len(CASES)}")
    print(f"\n  By course:")
    for code, meta in COURSES.items():
        cases = by_course(code)
        if cases:
            print(f"    {meta['label']:12} {len(cases)} cases")
    print(f"\n  High-data cases: {len([c for c in CASES if c.get('data_level')=='high'])}")
    print(f"  Gap plays (low data, high demand): {len([c for c in CASES if c.get('data_level')=='low'])}")
