"""
CPL case catalog — the products students can browse and buy.

Sourced from the existing case library in project knowledge:
- Harvey Hoya + aliases (HTN Stage 2)
- Bebe Babbitt + aliases (Migraine with Aura)
- Cynthia Francis (Hyperlipidemia)
- Samantha Graves + alias (Viral Gastroenteritis pediatric)
- Kennedy Poole (ADHD inattentive — peds academic decline)
- ...plus on-demand builds covering the rest of the common case library

Every case is orderable today. Some are battle-tested (multiple deliveries logged)
while others are on-demand builds — same workflow, same quality, but the very
first delivery of a new case may take an extra few hours for intake validation.

Each case has enough content for the preview page without revealing the answer keys.
"""

CASES = [
    {
        "slug": "harvey-hoya-htn",
        "title": "Harvey Hoya — Hypertension Stage 2",
        "patient_short": "57-year-old male",
        "chief_complaint": "High blood pressure noted at community health fair",
        "diagnosis": "Hypertension, Primary (Essential) — Stage 2 with target organ damage",
        "course": "NR 509 / NR 511 Week 5",
        "school": "Chamberlain University",
        "aliases": ["Harvey Hoya", "Anselmo Lopez", "Herbie Romero", "Felipe Garcia"],
        "must_not_miss": "Obstructive Sleep Apnea (OSA)",
        "key_scoring_traps": [
            "AV nicking on fundoscopy = target organ damage (often missed)",
            "Laterally displaced PMI = LVH (must palpate)",
            "Stage 2 requires two-drug therapy per ACC/AHA 2017",
            "35+ pack-year smoking history must be in key findings AND plan",
        ],
        "tags": ["Cardiovascular", "Adult"],
        "preview_hpi_count": 35,
        "preview_pe_count": 28,
        "preview_dx_count": 5,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "teal",
    },
    {
        "slug": "bebe-babbitt-migraine",
        "title": "Bebe Babbitt — Migraine with Aura",
        "patient_short": "26-year-old female",
        "chief_complaint": "More frequent severe headaches",
        "diagnosis": "Migraine with Aura",
        "course": "NR 509 Week 6",
        "school": "Chamberlain University",
        "aliases": ["Bebe Babbitt", "Marta Hernandez", "Jessica Walbertz", "Mabel Johnson"],
        "must_not_miss": "Cluster headache; secondary headache (SNOOP4 screen)",
        "key_scoring_traps": [
            "ORDER ZERO TESTS — normal exam, clinical diagnosis",
            "Ordering CT/MRI = 'harmful to patient' flag → Tests score 0%",
            "Pivotal communication question scored",
            "Photophobia/phonophobia must be documented in clinical terms",
        ],
        "tags": ["Neurologic", "Adult"],
        "preview_hpi_count": 32,
        "preview_pe_count": 24,
        "preview_dx_count": 4,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "lime",
    },
    {
        "slug": "cynthia-francis-hyperlipidemia",
        "title": "Cynthia Francis — Hyperlipidemia",
        "patient_short": "53-year-old female",
        "chief_complaint": "Follow-up after abnormal lipid panel",
        "diagnosis": "Hyperlipidemia / Mixed dyslipidemia",
        "course": "NR 509 / NR 511",
        "school": "Chamberlain University",
        "aliases": ["Cynthia Francis"],
        "must_not_miss": "Untreated hypothyroidism (secondary hyperlipidemia)",
        "key_scoring_traps": [
            "TSH must be ordered — rules out secondary cause",
            "Atorvastatin 20 mg starting dose, taken at bedtime",
            "Lifestyle counseling required even with statin",
            "Continue thyroid hormone replacement concurrently",
        ],
        "tags": ["Endocrine", "Adult"],
        "preview_hpi_count": 30,
        "preview_pe_count": 22,
        "preview_dx_count": 4,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "teal",
    },
    {
        "slug": "samantha-graves-gastroenteritis",
        "title": "Samantha Graves — Viral Gastroenteritis",
        "patient_short": "5-year-old female",
        "chief_complaint": "Vomiting and diarrhea ×2 days",
        "diagnosis": "Acute viral gastroenteritis with mild dehydration",
        "course": "NR 602 Week 5",
        "school": "Chamberlain University",
        "aliases": ["Samantha Graves", "Courtney Graham"],
        "must_not_miss": "Bacterial gastroenteritis; severe dehydration; intussusception",
        "key_scoring_traps": [
            "Order zero tests for uncomplicated pediatric viral GE",
            "ORS (Pedialyte) — small frequent sips, not antiemetics",
            "Capillary refill + skin turgor scored on PE",
            "Parent education on dehydration warning signs critical",
        ],
        "tags": ["GI", "Pediatric"],
        "preview_hpi_count": 28,
        "preview_pe_count": 26,
        "preview_dx_count": 4,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "lime",
    },
    {
        "slug": "kennedy-poole-adhd",
        "title": "Kennedy Poole — ADHD, Inattentive",
        "patient_short": "10-year-old female",
        "chief_complaint": "Slipping grades and academic decline",
        "diagnosis": "ADHD, Predominantly Inattentive (F90.0)",
        "course": "NR 602 Week 4",
        "school": "Chamberlain University",
        "aliases": ["Kennedy Poole"],
        "must_not_miss": "Vision/hearing impairment; learning disorder; depression; absence seizures",
        "key_scoring_traps": [
            "History questions go to PARENT, not child",
            "Vanderbilt rating scales (parent + teacher) — must order",
            "Methylphenidate ER 18 mg starting dose; Schedule II",
            "Baseline ECG before stimulant start",
        ],
        "tags": ["Mental Health", "Pediatric"],
        "preview_hpi_count": 38,
        "preview_pe_count": 22,
        "preview_dx_count": 5,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "ink",
    },
    {
        "slug": "victoria-lewis",
        "title": "Victoria Lewis — Adult Case",
        "patient_short": "Adult female",
        "chief_complaint": "[Available after intake]",
        "diagnosis": "[Available after intake]",
        "course": "Chamberlain — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Victoria Lewis"],
        "must_not_miss": "Confirmed at delivery",
        "key_scoring_traps": [
            "Full scoring strategy provided on delivery",
            "Built from verified student submissions",
        ],
        "tags": ["Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "teal",
    },
    {
        "slug": "betty-burns-pt1",
        "title": "Betty Burns Part 1",
        "patient_short": "Adult female",
        "chief_complaint": "[Available after intake]",
        "diagnosis": "[Available after intake]",
        "course": "Chamberlain — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Betty Burns"],
        "must_not_miss": "Confirmed at delivery",
        "key_scoring_traps": [
            "Part 1 of two-part case sequence",
            "Full scoring strategy on delivery",
        ],
        "tags": ["Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "lime",
    },
    {
        "slug": "betty-burns-pt2",
        "title": "Betty Burns Part 2",
        "patient_short": "Adult female",
        "chief_complaint": "[Available after intake]",
        "diagnosis": "[Available after intake]",
        "course": "Chamberlain — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Betty Burns"],
        "must_not_miss": "Confirmed at delivery",
        "key_scoring_traps": [
            "Part 2 follow-up case",
            "Continues from Part 1 patient",
        ],
        "tags": ["Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "ink",
    },
    {
        "slug": "christine-smith-pyelonephritis",
        "title": "Christine Smith — Pyelonephritis",
        "patient_short": "Adult female",
        "chief_complaint": "Flank pain, fever, dysuria",
        "diagnosis": "Acute pyelonephritis",
        "course": "NRNP 6531 Week 7",
        "school": "Walden University",
        "aliases": ["Christine Smith"],
        "must_not_miss": "Sepsis / urosepsis; obstructive nephrolithiasis",
        "key_scoring_traps": [
            "CVA tenderness — must elicit and document",
            "Empiric antibiotic before culture results back",
            "Urine culture + sensitivity required",
            "Inpatient vs. outpatient threshold criteria",
        ],
        "tags": ["GU", "Adult"],
        "preview_hpi_count": 30,
        "preview_pe_count": 24,
        "preview_dx_count": 4,
        "status": "ready",
        "lead_time": "same-day",
        "color_accent": "teal",
    },
    {
        "slug": "amanda-wheaton-pharyngitis",
        "title": "Amanda Wheaton — GAS Pharyngitis",
        "patient_short": "Young adult female",
        "chief_complaint": "Sore throat ×3 days",
        "diagnosis": "Group A Streptococcal pharyngitis",
        "course": "NR 509 — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Amanda Wheaton"],
        "must_not_miss": "Peritonsillar abscess; infectious mononucleosis; epiglottitis",
        "key_scoring_traps": [
            "Centor criteria scored — must apply",
            "Penicillin V 500 mg BID × 10 days (full course)",
            "Rapid strep test indicated, throat culture if negative",
            "Tonsillar exudate + anterior cervical LAN are pertinent positives",
        ],
        "tags": ["ENT", "Adult"],
        "preview_hpi_count": 28,
        "preview_pe_count": 22,
        "preview_dx_count": 4,
        "status": "ready",
        "lead_time": "fast-build",
        "color_accent": "lime",
    },
    {
        "slug": "tina-jones-shadow-health",
        "title": "Tina Jones — Shadow Health",
        "patient_short": "28-year-old female",
        "chief_complaint": "Multiple — Tina Jones case series",
        "diagnosis": "Various (per assignment)",
        "course": "NURS 6512 / various",
        "school": "Walden University",
        "aliases": ["Tina Jones"],
        "must_not_miss": "Diabetes Type 2 management complications",
        "key_scoring_traps": [
            "Shadow Health (not iHuman) — different scoring rubric",
            "DCE empathy scoring — phrasing matters",
            "Pertinent negatives must be explicitly documented",
            "Comprehensive vs focused assessment per assignment",
        ],
        "tags": ["Shadow Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "fast-build",
        "color_accent": "teal",
    },
    {
        "slug": "tanner-bell-uri",
        "title": "Tanner Bell — Pediatric URI",
        "patient_short": "4-year-old male",
        "chief_complaint": "Cough and runny nose ×5 days",
        "diagnosis": "Viral upper respiratory infection",
        "course": "NR 602 — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Tanner Bell"],
        "must_not_miss": "Bacterial pneumonia; otitis media; RSV bronchiolitis",
        "key_scoring_traps": [
            "Don't order chest X-ray for uncomplicated URI",
            "Symptomatic management — no antibiotics",
            "Parent education on duration + red flags",
            "Otoscopic exam required",
        ],
        "tags": ["Respiratory", "Pediatric"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "fast-build",
        "color_accent": "ink",
    },
    {
        "slug": "lori-jacobs-uti",
        "title": "Lori Jacobs — UTI",
        "patient_short": "Adult female",
        "chief_complaint": "Dysuria and urinary frequency",
        "diagnosis": "Uncomplicated urinary tract infection",
        "course": "NR 511 — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Lori Jacobs"],
        "must_not_miss": "Pyelonephritis; STI; pregnancy",
        "key_scoring_traps": [
            "Pregnancy test before antibiotics in reproductive-age females",
            "Nitrofurantoin first-line for uncomplicated UTI",
            "Urine dipstick + culture",
            "Patient education on hydration + completion of course",
        ],
        "tags": ["GU", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "fast-build",
        "color_accent": "lime",
    },
    {
        "slug": "geriatric-fall",
        "title": "Geriatric Patient — Fall Risk",
        "patient_short": "Adult patient",
        "chief_complaint": "Recent fall, mobility concern",
        "diagnosis": "Multifactorial fall risk",
        "course": "NRNP — verify with intake",
        "school": "Walden University",
        "aliases": ["Various"],
        "must_not_miss": "Syncope; medication-induced orthostasis; subdural",
        "key_scoring_traps": [
            "Orthostatic vital signs — must perform",
            "Medication reconciliation — beers list review",
            "Gait + Tinetti assessment",
            "Home safety + PT referral",
        ],
        "tags": ["Geriatric", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "fast-build",
        "color_accent": "teal",
    },
    {
        "slug": "depression-anxiety",
        "title": "Adult — Depression Screen",
        "patient_short": "Adult patient",
        "chief_complaint": "Low mood, fatigue",
        "diagnosis": "Major depressive disorder",
        "course": "NRNP 6541 — verify with intake",
        "school": "Walden University",
        "aliases": ["Various"],
        "must_not_miss": "Bipolar disorder; suicide risk; hypothyroidism",
        "key_scoring_traps": [
            "PHQ-9 + GAD-7 must be administered",
            "Suicide risk assessment — explicit documentation",
            "TSH ordered to rule out hypothyroid",
            "SSRI choice + dose + tolerability monitoring",
        ],
        "tags": ["Mental Health", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "fast-build",
        "color_accent": "ink",
    },
    {
        "slug": "type-2-diabetes",
        "title": "Adult — New Type 2 Diabetes",
        "patient_short": "Adult patient",
        "chief_complaint": "Polyuria, polydipsia, weight loss",
        "diagnosis": "Diabetes mellitus, type 2 — new diagnosis",
        "course": "NR 511 — verify with intake",
        "school": "Chamberlain University",
        "aliases": ["Various"],
        "must_not_miss": "DKA; HHS; type 1 vs type 2",
        "key_scoring_traps": [
            "HbA1c + fasting glucose + lipid panel",
            "Metformin first-line; titrate dose",
            "Dilated eye exam referral",
            "DSME (diabetes self-management education) — required",
        ],
        "tags": ["Endocrine", "Adult"],
        "preview_hpi_count": None,
        "preview_pe_count": None,
        "preview_dx_count": None,
        "status": "ready",
        "lead_time": "fast-build",
        "color_accent": "lime",
    },
]

# Pricing tiers
PRICING = {
    "single":  {"price": 150, "label": "Single guide", "saves": 0,
                "blurb": "One complete case, delivered same day."},
    "bundle3": {"price": 390, "label": "3-case bundle", "saves": 60,
                "blurb": "Save $60. Mix any 3 cases."},
    "bundle5": {"price": 540, "label": "5-case bundle", "saves": 210,
                "blurb": "Save $210. Best value for a full term."},
}

def by_status(status):
    return [c for c in CASES if c.get("status") == status]

def by_slug(slug):
    for c in CASES:
        if c["slug"] == slug:
            return c
    return None

if __name__ == "__main__":
    print(f"CPL Case Catalog: {len(CASES)} cases total")
    print(f"  Battle-tested: {len([c for c in CASES if c.get('lead_time') == 'same-day'])}")
    print(f"  On-demand:     {len([c for c in CASES if c.get('lead_time') == 'fast-build'])}")
    print(f"  All orderable today.")
